workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
     
    scripts:
      - flutter packages pub get
      - flutter analyze
      - flutter test
      - flutter build apk --no-sound-null-safety --release --build-name=1.0.0
      
    environment:
      flutter: stable
      xcode: latest
    artifacts:
      - build/**/outputs/apk/**/*.apk
      
      