workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120

     
    scripts:
      - flutter packages pub get
      - flutter build ios --no-sound-null-safety --release  
      # - flutter build ios --no-sound-null-safety --release --no-codesign 
      # - flutter build apk --no-sound-null-safety --debug --build-name=1.0.0  
    environment:
      vars:
          XCODE_WORKSPACE: "Runner.xcworkspace"  

      flutter: stable
      xcode: latest
    artifacts:
      # - build/ios/ipa/*.ipa
      # - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      # - build/**/outputs/apk/**/*.apk
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/*.app





# workflows:
#   ios-workflow:
#     name: iOS Workflow
#     # instance_type: mac_mini
#     max_build_duration: 120
#     environment:
      
#       flutter: stable
#       xcode: latest
#       - name: Get Flutter packages
#         script: |
#           flutter packages pub get
#       - name: Flutter build ipa and automatic versioning
#         script: |
#           flutter build ios --no-sound-null-safety --release --no-codesign --build-name=1.0.0     
#     artifacts:
#       - build/ios/ipa/*.ipa
#       - /tmp/xcodebuild_logs/*.log
#       - flutter_drive.log
   
      