workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
     
    scripts:
      - flutter packages pub get
      - flutter build ios --no-sound-null-safety --debug --build-name=1.0.0
      # - flutter build apk --no-sound-null-safety --debug --build-name=1.0.0
      
      
    environment:
      flutter: stable
      xcode: latest
    artifacts:
      - build/**/outputs/ipa/**/*.ipa
      # - build/ios/ipa/*.ipa
      # - build/**/outputs/apk/**/*.apk
      
      